// GENERATED FILE — DO NOT EDIT.
//
// The words the one-device game draws on. Generated from
// server/internal/content by "go run ./cmd/exportwords", because a game with
// no server still needs them on the device, and a second hand-written list is
// a list that drifts. The Go test guarding this fails if the two fall out of
// step.

/// A category and the words it can produce.
class LocalCategory {
  const LocalCategory(this.id, this.name, this.words);

  final String id;
  final String name;
  final List<String> words;
}

/// Each language's categories, by language code
/// (server/internal/content/languages/<code>.json).
const localContent = <String, List<LocalCategory>>{
  'en': [
    LocalCategory('food', 'Food & Drink', [
      'Pizza',
      'Burger',
      'Taco',
      'Burrito',
      'Hot dog',
      'Falafel',
      'Shawarma',
      'Sushi',
      'Ramen',
      'Pasta',
      'Lasagna',
      'Curry',
      'Fried rice',
      'Pancake',
      'Waffle',
      'Omelette',
      'Cereal',
      'Bagel',
      'Croissant',
      'Toast',
      'Sandwich',
      'Salad',
      'Soup',
      'Steak',
      'French fries',
      'Popcorn',
      'Nachos',
      'Pretzel',
      'Donut',
      'Cookie',
      'Brownie',
      'Cheesecake',
      'Ice cream',
      'Chocolate',
      'Hummus',
      'Guacamole',
      'Ketchup',
      'Mustard',
      'Honey',
      'Cheese',
      'Coffee',
      'Tea',
      'Hot chocolate',
      'Lemonade',
      'Cola',
      'Smoothie',
      'Milkshake',
      'Orange juice',
      'Beer',
      'Cocktail',
      'Apple',
      'Banana',
      'Rice',
      'Bread',
      'Watermelon',
    ]),
    LocalCategory('animals', 'Animals', [
      'Dog',
      'Cat',
      'Rabbit',
      'Hamster',
      'Horse',
      'Cow',
      'Sheep',
      'Goat',
      'Pig',
      'Chicken',
      'Lion',
      'Tiger',
      'Elephant',
      'Giraffe',
      'Zebra',
      'Monkey',
      'Gorilla',
      'Bear',
      'Panda',
      'Kangaroo',
      'Koala',
      'Penguin',
      'Dolphin',
      'Whale',
      'Shark',
      'Octopus',
      'Turtle',
      'Crocodile',
      'Snake',
      'Frog',
      'Eagle',
      'Owl',
      'Parrot',
      'Flamingo',
      'Peacock',
      'Butterfly',
      'Bee',
      'Spider',
      'Ant',
      'Ladybug',
      'Wolf',
      'Fox',
      'Deer',
      'Camel',
      'Squirrel',
      'Leopard',
      'Cheetah',
      'Hippopotamus',
      'Rhinoceros',
      'Moose',
      'Raccoon',
      'Hedgehog',
      'Chameleon',
      'Seal',
      'Jellyfish',
    ]),
    LocalCategory('home', 'At Home', [
      'Fridge',
      'Freezer',
      'Oven',
      'Microwave',
      'Dishwasher',
      'Toaster',
      'Kettle',
      'Blender',
      'Air fryer',
      'Vacuum cleaner',
      'Broom',
      'Mop',
      'Washing machine',
      'Dryer',
      'Iron',
      'Sofa',
      'Armchair',
      'Coffee table',
      'Dining table',
      'Chair',
      'Bed',
      'Pillow',
      'Blanket',
      'Mattress',
      'Wardrobe',
      'Drawer',
      'Shelf',
      'Mirror',
      'Shower',
      'Bathtub',
      'Toilet',
      'Sink',
      'Towel',
      'Lamp',
      'Curtain',
      'Rug',
      'Window',
      'Doorbell',
      'Air conditioner',
      'Trash can',
      'Clock',
      'Television',
      'Remote control',
      'Bookshelf',
      'Desk',
      'Candle',
      'Laundry basket',
      'Hanger',
      'Doormat',
      'Vase',
    ]),
    LocalCategory('school_students', 'School & College', [
      'Pencil',
      'Pen',
      'Eraser',
      'Sharpener',
      'Highlighter',
      'Notebook',
      'Lunchbox',
      'Textbook',
      'Calculator',
      'Ruler',
      'Whiteboard',
      'Projector',
      'Classroom',
      'Locker',
      'Library',
      'Cafeteria',
      'Playground',
      'School bus',
      'Teacher',
      'Principal',
      'Professor',
      'Student',
      'Homework',
      'Exam',
      'Quiz',
      'Essay',
      'Grade',
      'Recess',
      'Detention',
      'Graduation',
      'Diploma',
      'Lecture',
      'Presentation',
      'Group project',
      'Yearbook',
      'Crayon',
      'Glue stick',
      'Scissors',
      'School uniform',
      'School trip',
      'Chalk',
      'Campus',
      'Dormitory',
      'Globe',
      'School bell',
    ]),
    LocalCategory('work_office', 'Jobs & Work', [
      'Doctor',
      'Nurse',
      'Architect',
      'Chef',
      'Waiter',
      'Pilot',
      'Police officer',
      'Firefighter',
      'Lawyer',
      'Engineer',
      'Programmer',
      'Designer',
      'Photographer',
      'Mechanic',
      'Electrician',
      'Plumber',
      'Carpenter',
      'Farmer',
      'Dentist',
      'Veterinarian',
      'Hairdresser',
      'Cashier',
      'Driver',
      'Baker',
      'Accountant',
      'Receptionist',
      'Journalist',
      'Manager',
      'Lifeguard',
      'Clown',
      'Tailor',
      'Detective',
      'Librarian',
      'Surgeon',
      'Painter',
      'Gardener',
      'Secretary',
      'Barista',
      'Office',
      'Kindergarten teacher',
      'Pharmacist',
      'Scientist',
      'Astronaut',
      'Soldier',
      'Coach',
      'Construction worker',
      'Mail carrier',
      'Flight attendant',
      'Real estate agent',
      'Security guard',
    ]),
    LocalCategory('technology_digital', 'Tech & Digital', [
      'Smartphone',
      'Laptop',
      'Tablet',
      'Smartwatch',
      'Headphones',
      'Computer keyboard',
      'Mouse',
      'Monitor',
      'Printer',
      'Webcam',
      'Charger',
      'Battery',
      'Power bank',
      'USB drive',
      'Router',
      'WiFi',
      'Bluetooth',
      'Hotspot',
      'Password',
      'Face ID',
      'Screenshot',
      'Notification',
      'Email',
      'Browser',
      'Search engine',
      'Website',
      'App',
      'Social media',
      'Cloud storage',
      'Backup',
      'Download',
      'Streaming',
      'Video call',
      'QR code',
      'Robot',
      'Drone',
      'Virtual reality',
      'Artificial intelligence',
      'Chatbot',
      'Video game console',
      'Camera',
      'Bluetooth speaker',
      'Earbuds',
      'Smart TV',
      'Ebook reader',
      'Hacker',
      'Memory card',
      'Cable',
      'Adapter',
      'Touchscreen',
      'Barcode',
      'Voice assistant',
      'GPS',
      'Satellite',
      'Smart glasses',
    ]),
    LocalCategory('travel_vacation', 'Travel & Vacation', [
      'Passport',
      'Visa',
      'Plane ticket',
      'Boarding pass',
      'Airport',
      'Suitcase',
      'Backpack',
      'Hotel',
      'Hostel',
      'Resort',
      'Campsite',
      'Cruise',
      'Beach',
      'Swimming pool',
      'Sunscreen',
      'Souvenir',
      'Map',
      'Tour guide',
      'Museum',
      'Road trip',
      'Train',
      'Taxi',
      'Rental car',
      'Ferry',
      'Cable car',
      'Snorkeling',
      'Hiking',
      'Check in',
      'Security check',
      'Boarding gate',
      'Takeoff',
      'Landing',
      'Duty free',
      'Jet lag',
      'Postcard',
      'Sleeping bag',
      'Room service',
      'Reception desk',
      'Luggage tag',
      'Beach towel',
      'Travel pillow',
      'Binoculars',
      'Compass',
      'Theme park',
      'Water park',
    ]),
    LocalCategory('places', 'Places Around the World', [
      'Paris',
      'London',
      'Rome',
      'Barcelona',
      'Amsterdam',
      'Prague',
      'Vienna',
      'Budapest',
      'Berlin',
      'Athens',
      'Venice',
      'New York',
      'Los Angeles',
      'Miami',
      'Las Vegas',
      'Toronto',
      'Rio de Janeiro',
      'Mexico City',
      'Tokyo',
      'Seoul',
      'Bangkok',
      'Singapore',
      'Hong Kong',
      'Dubai',
      'Jerusalem',
      'Cairo',
      'Sydney',
      'Bali',
      'Hawaii',
      'Maldives',
      'Iceland',
      'Lapland',
      'Sahara Desert',
      'Amazon rainforest',
      'Grand Canyon',
      'Niagara Falls',
      'Mount Everest',
      'Swiss Alps',
      'Eiffel Tower',
      'Big Ben',
      'Colosseum',
      'Pyramids of Giza',
      'Great Wall of China',
      'Machu Picchu',
      'Statue of Liberty',
      'Madrid',
      'Lisbon',
      'Dublin',
      'Copenhagen',
      'Stockholm',
      'Istanbul',
      'Cape Town',
      'Marrakech',
      'Beijing',
      'Shanghai',
      'Delhi',
      'Mumbai',
      'Phuket',
      'Santorini',
      'Petra',
    ]),
    LocalCategory('dating_relationships', 'Dating & Relationships', [
      'Dating app',
      'Match',
      'Swipe',
      'Profile',
      'Message',
      'Phone number',
      'First date',
      'Coffee date',
      'Crush',
      'Bouquet',
      'Teddy bear',
      'Valentine\'s Day',
      'Flirting',
      'Compliment',
      'Smile',
      'Kiss',
      'Love',
      'Hug',
      'Partner',
      'Couple',
      'Love song',
      'Jealousy',
      'Argument',
      'Apology',
      'Double date',
      'Anniversary',
      'Proposal',
      'Engagement ring',
      'Wedding',
      'Breakup',
      'Blind date',
      'Ex',
      'Love letter',
      'Date night',
      'Honeymoon',
    ]),
    LocalCategory('nightlife', 'Nightlife & Parties', [
      'Bar',
      'Pub',
      'Nightclub',
      'House party',
      'Birthday party',
      'Live band',
      'Bouncer',
      'Guest list',
      'Wristband',
      'DJ',
      'Dance floor',
      'Speaker',
      'Dance battle',
      'Champagne',
      'Wine',
      'Shot',
      'Bartender',
      'Neon lights',
      'Laser',
      'Confetti',
      'Disco ball',
      'Selfie',
      'Dancing',
      'Afterparty',
      'Hangover',
      'Comedy club',
      'Rooftop party',
      'Escape room',
      'Billiards',
      'Arcade',
      'Casino',
      'Glow sticks',
      'Party invitation',
      'Birthday cake',
      'Gift',
      'Balloons',
      'Costume party',
      'Photo booth',
      'Party hat',
      'Fireworks',
    ]),
    LocalCategory('fashion_grooming', 'Fashion & Grooming', [
      'T shirt',
      'Sweater',
      'Hoodie',
      'Shirt',
      'Jeans',
      'Trousers',
      'Shorts',
      'Skirt',
      'Dress',
      'Leggings',
      'Suit',
      'Jacket',
      'Coat',
      'Raincoat',
      'Sneakers',
      'Boots',
      'Sandals',
      'Flip flops',
      'High heels',
      'Hat',
      'Sunglasses',
      'Belt',
      'Scarf',
      'Handbag',
      'Watch',
      'Necklace',
      'Bracelet',
      'Earrings',
      'Lipstick',
      'Mascara',
      'Perfume',
      'Deodorant',
      'Haircut',
      'Manicure',
      'Fitting room',
      'Blouse',
      'Polo shirt',
      'Tank top',
      'Cardigan',
      'Blazer',
      'Vest',
      'Swimsuit',
      'Pajamas',
      'Nail polish',
      'Hair dryer',
    ]),
    LocalCategory('gaming', 'Gaming', [
      'PlayStation',
      'Xbox',
      'Nintendo Switch',
      'Joystick',
      'Mobile game',
      'Minecraft',
      'Fortnite',
      'Roblox',
      'Mario',
      'Pokémon',
      'The Legend of Zelda',
      'Grand Theft Auto',
      'FIFA',
      'Tetris',
      'Among Us',
      'Controller',
      'Multiplayer',
      'Lobby',
      'Teammate',
      'Opponent',
      'Level',
      'Boss',
      'Quest',
      'Checkpoint',
      'Score',
      'Leaderboard',
      'Tournament',
      'Victory',
      'Defeat',
      'Rematch',
      'Skin',
      'Loot',
      'Respawn',
      'Lag',
      'Game over',
      'Call of Duty',
      'The Sims',
      'Animal Crossing',
      'Sonic',
      'Pac Man',
      'League of Legends',
      'Valorant',
      'Rocket League',
      'Gaming headset',
      'Cheat code',
      'Split screen',
      'Speedrun',
      'Achievement',
      'Power up',
      'Health bar',
    ]),
    LocalCategory('music', 'Music', [
      'Guitar',
      'Piano',
      'Violin',
      'Drums',
      'Saxophone',
      'Trumpet',
      'Flute',
      'Harmonica',
      'Microphone',
      'Singer',
      'Band',
      'Orchestra',
      'Concert',
      'Festival',
      'Stage',
      'Audience',
      'Backstage',
      'Recording studio',
      'Album',
      'Single',
      'Playlist',
      'Chorus',
      'Verse',
      'Lyrics',
      'Melody',
      'Rhythm',
      'Remix',
      'Karaoke',
      'Pop',
      'Rock',
      'Hip hop',
      'Jazz',
      'Classical music',
      'Electronic music',
      'Country music',
      'Cello',
      'Ukulele',
      'Keyboard',
      'Accordion',
      'Tambourine',
      'Xylophone',
      'Clarinet',
      'Bass guitar',
      'Composer',
      'Conductor',
      'Songwriter',
      'Music video',
      'Radio',
      'Opera',
      'Grammy',
    ]),
    LocalCategory('nostalgia', 'Nostalgia', [
      'Walkman',
      'Discman',
      'Game Boy',
      'Tamagotchi',
      'Nokia phone',
      'Cassette tape',
      'VHS tape',
      'Floppy disk',
      'CD player',
      'Film camera',
      'Dial up internet',
      'Internet cafe',
      'MSN Messenger',
      'MySpace',
      'Windows XP',
      'Internet Explorer',
      'Winamp',
      'Minesweeper',
      'Solitaire',
      'Pager',
      'Landline',
      'Payphone',
      'Phone book',
      'Rotary phone',
      'Disposable camera',
      'Photo album',
      'Arcade machine',
      'Pinball',
      'Sticker album',
      'Pokémon cards',
      'Pogs',
      'Marbles',
      'Yoyo',
      'Jump rope',
      'Hopscotch',
      'Phone card',
      'Answering machine',
      'Slide projector',
      'Comic book',
      'Saturday cartoons',
    ]),
    LocalCategory('internet_culture', 'Internet Culture', [
      'Meme',
      'Emoji',
      'GIF',
      'Hashtag',
      'Selfie stick',
      'Viral video',
      'Influencer',
      'Follower',
      'Subscriber',
      'Livestream',
      'Streamer',
      'Podcast',
      'Reaction video',
      'Unboxing',
      'Online challenge',
      'Clickbait',
      'Spoiler',
      'Troll',
      'Spam',
      'Bot',
      'Username',
      'Profile picture',
      'Direct message',
      'Group chat',
      'Like button',
      'Comment section',
      'Algorithm',
      'FOMO',
      'LOL',
      'Trending',
      'TikTok',
      'Fan page',
      'Online forum',
      'Video thumbnail',
      'Verification badge',
    ]),
    LocalCategory('superheroes_fantasy', 'Superheroes & Fantasy', [
      'Superman',
      'Batman',
      'Spider Man',
      'Wonder Woman',
      'Iron Man',
      'Hulk',
      'Thor',
      'Captain America',
      'Black Panther',
      'Deadpool',
      'Joker',
      'Thanos',
      'Voldemort',
      'Darth Vader',
      'Wizard',
      'Witch',
      'Dragon',
      'Unicorn',
      'Mermaid',
      'Vampire',
      'Werewolf',
      'Fairy',
      'Elf',
      'Goblin',
      'Giant',
      'Knight',
      'Princess',
      'King',
      'Queen',
      'Castle',
      'Dungeon',
      'Magic wand',
      'Spell',
      'Potion',
      'Sword',
      'Shield',
      'Cape',
      'Mask',
      'Superpower',
      'Secret identity',
      'Sauron',
      'Gandalf',
      'Dumbledore',
      'Genie',
      'Centaur',
      'Phoenix',
      'Ogre',
      'Treasure map',
      'Time machine',
      'Lightsaber',
    ]),
    LocalCategory('film_tv', 'Movies & TV', [
      'Titanic',
      'Avatar',
      'Frozen',
      'Shrek',
      'Toy Story',
      'The Lion King',
      'Jurassic Park',
      'Harry Potter',
      'Star Wars',
      'The Matrix',
      'Finding Nemo',
      'Home Alone',
      'Pirates of the Caribbean',
      'Back to the Future',
      'The Avengers',
      'Friends',
      'The Office',
      'Breaking Bad',
      'Game of Thrones',
      'Stranger Things',
      'Squid Game',
      'The Simpsons',
      'SpongeBob SquarePants',
      'Peppa Pig',
      'Reality show',
      'Game show',
      'Talk show',
      'Documentary',
      'Comedy',
      'Horror',
      'Action movie',
      'Animation',
      'Director',
      'Actor',
      'Villain',
      'Plot twist',
      'Trailer',
      'Movie ticket',
      'Movie theater',
      'Streaming service',
      'Jaws',
      'ET',
      'Rocky',
      'Ghostbusters',
      'Men in Black',
      'The Godfather',
      'Pulp Fiction',
      'Forrest Gump',
      'Jumanji',
      'The Karate Kid',
      'Despicable Me',
      'Minions',
      'Moana',
      'Encanto',
      'The Crown',
      'Black Mirror',
      'Money Heist',
      'Wednesday',
      'Movie star',
      'Subtitles',
    ]),
    LocalCategory('sports', 'Sports & Fitness', [
      'Football',
      'Basketball',
      'Volleyball',
      'Baseball',
      'Rugby',
      'Hockey',
      'Tennis',
      'Padel',
      'Table tennis',
      'Badminton',
      'Squash',
      'Boxing',
      'Judo',
      'Karate',
      'Wrestling',
      'Swimming',
      'Surfing',
      'Rowing',
      'Kayaking',
      'Diving',
      'Running',
      'Cycling',
      'Marathon',
      'Triathlon',
      'Gymnastics',
      'Weightlifting',
      'Treadmill',
      'Dumbbell',
      'Barbell',
      'Squat',
      'Push up',
      'Pull up',
      'Plank',
      'Skiing',
      'Snowboarding',
      'Ice skating',
      'Golf',
      'Darts',
      'Bowling',
      'Archery',
      'Referee',
      'Scoreboard',
      'Medal',
      'Trophy',
      'Podium',
      'Handball',
      'Cricket',
      'American football',
      'Lacrosse',
      'Taekwondo',
      'Fencing',
      'Sailing',
      'Canoeing',
      'Rock climbing',
      'Skateboarding',
      'Yoga',
      'Pilates',
      'Kettlebell',
      'Resistance band',
      'Whistle',
    ]),
    LocalCategory('nature_weather', 'Nature & Weather', [
      'Sun',
      'Moon',
      'Star',
      'Rainbow',
      'Cloud',
      'Rain',
      'Snow',
      'Thunder',
      'Lightning',
      'Wind',
      'Tornado',
      'Hurricane',
      'Volcano',
      'Earthquake',
      'Mountain',
      'Valley',
      'River',
      'Lake',
      'Waterfall',
      'Ocean',
      'Island',
      'Desert',
      'Forest',
      'Jungle',
      'Cave',
      'Canyon',
      'Glacier',
      'Cliff',
      'Meadow',
      'Tree',
      'Flower',
      'Rose',
      'Sunflower',
      'Cactus',
      'Mushroom',
      'Leaf',
      'Pine cone',
      'Pebble',
      'Sand',
      'Coral reef',
      'Wave',
      'Sunset',
      'Sunrise',
      'Northern lights',
      'Water',
    ]),
    LocalCategory('transportation', 'Transportation', [
      'Car',
      'Bus',
      'Airplane',
      'Helicopter',
      'Bicycle',
      'Motorcycle',
      'Scooter',
      'Truck',
      'Van',
      'Ambulance',
      'Fire engine',
      'Police car',
      'Tram',
      'Subway',
      'High speed train',
      'Boat',
      'Ship',
      'Yacht',
      'Sailboat',
      'Jet ski',
      'Hot air balloon',
      'Gondola',
      'Rickshaw',
      'Tuk tuk',
      'Limousine',
      'Camper van',
      'Tractor',
      'Bulldozer',
      'Forklift',
      'Skateboard',
      'Roller skates',
      'Wheelchair',
      'Stroller',
      'Elevator',
      'Escalator',
    ]),
    LocalCategory('hobbies_free_time', 'Hobbies & Free Time', [
      'Reading',
      'Cooking',
      'Baking',
      'Gardening',
      'Painting',
      'Drawing',
      'Photography',
      'Knitting',
      'Sewing',
      'Fishing',
      'Camping',
      'Dance lessons',
      'Singing',
      'Chess',
      'Puzzles',
      'Collecting',
      'Birdwatching',
      'Stargazing',
      'Pottery',
      'Woodworking',
      'Origami',
      'Calligraphy',
      'Scrapbooking',
      'Journaling',
      'Meditation',
      'Magic tricks',
      'Model building',
      'Coin collecting',
      'Stamp collecting',
      'Board games',
      'Card games',
      'Crosswords',
      'Sudoku',
      'Acting',
      'Lego',
      'Vlogging',
      'Volunteering',
      'Language learning',
      'Kite flying',
      'Picnicking',
    ]),
  ],
  'he': [
    LocalCategory('food', 'אוכל ושתייה', [
      'פיצה',
      'המבורגר',
      'טאקו',
      'בוריטו',
      'נקניקייה',
      'פלאפל',
      'שווארמה',
      'סושי',
      'ראמן',
      'פסטה',
      'לזניה',
      'קארי',
      'ג\'חנון',
      'פנקייק',
      'ופל',
      'חביתה',
      'קורנפלקס',
      'בורקס',
      'קרואסון',
      'טוסט',
      'כריך',
      'סלט',
      'מרק',
      'סטייק',
      'צ\'יפס',
      'פופקורן',
      'במבה',
      'בייגלה',
      'דונאט',
      'עוגייה',
      'בראוניז',
      'עוגת גבינה',
      'גלידה',
      'שוקולד',
      'חומוס',
      'שקשוקה',
      'קטשופ',
      'שניצל',
      'דבש',
      'גבינה',
      'קפה',
      'תה',
      'שוקו חם',
      'לימונדה',
      'קולה',
      'קרטיב',
      'מילקשייק',
      'מיץ תפוזים',
      'בירה',
      'קוקטייל',
      'תפוח',
      'בננה',
      'אורז',
      'לחם',
      'אבטיח',
    ]),
    LocalCategory('animals', 'בעלי חיים', [
      'כלב',
      'חתול',
      'ארנב',
      'אוגר',
      'סוס',
      'פרה',
      'כבשה',
      'עז',
      'חזיר',
      'תרנגולת',
      'אריה',
      'נמר',
      'פיל',
      'ג\'ירפה',
      'זברה',
      'קוף',
      'גורילה',
      'דוב',
      'פנדה',
      'קנגורו',
      'קואלה',
      'פינגווין',
      'דולפין',
      'לווייתן',
      'כריש',
      'תמנון',
      'צב',
      'תנין',
      'נחש',
      'צפרדע',
      'נשר',
      'ינשוף',
      'תוכי',
      'פלמינגו',
      'טווס',
      'פרפר',
      'דבורה',
      'עכביש',
      'נמלה',
      'פרת משה רבנו',
      'זאב',
      'שועל',
      'אייל',
      'גמל',
      'סנאי',
      'ברדלס',
      'היפופוטם',
      'קרנף',
      'אייל קורא',
      'דביבון',
      'קיפוד',
      'זיקית',
      'כלב ים',
      'מדוזה',
      'לוטרה',
    ]),
    LocalCategory('home', 'בבית', [
      'מקרר',
      'מקפיא',
      'תנור',
      'מיקרוגל',
      'מדיח כלים',
      'טוסטר',
      'קומקום',
      'בלנדר',
      'אייר פרייר',
      'שואב אבק',
      'מטאטא',
      'מגב',
      'מכונת כביסה',
      'מייבש כביסה',
      'מגהץ',
      'ספה',
      'כורסה',
      'שולחן סלון',
      'שולחן אוכל',
      'כיסא',
      'מיטה',
      'כרית',
      'שמיכה',
      'מזרן',
      'ארון בגדים',
      'מגירה',
      'מדף',
      'מראה',
      'מקלחת',
      'אמבטיה',
      'אסלה',
      'כיור',
      'מגבת',
      'מנורה',
      'וילון',
      'שטיח',
      'חלון',
      'פעמון דלת',
      'מזגן',
      'פח אשפה',
      'שעון קיר',
      'טלוויזיה',
      'שלט',
      'כוננית',
      'שולחן כתיבה',
      'נר',
      'סל כביסה',
      'קולב',
      'שטיח כניסה',
      'אגרטל',
    ]),
    LocalCategory('school_students', 'בית ספר ולימודים', [
      'עיפרון',
      'עט',
      'מחק',
      'מחדד',
      'מרקר',
      'מחברת',
      'קופסת אוכל',
      'ספר לימוד',
      'מחשבון',
      'סרגל',
      'לוח',
      'מקרן',
      'כיתה',
      'לוקר',
      'ספרייה',
      'קפטריה',
      'מגרש משחקים',
      'הסעה',
      'מורה',
      'מנהל בית ספר',
      'מרצה',
      'תלמיד',
      'שיעורי בית',
      'מבחן',
      'בוחן',
      'חיבור',
      'ציון',
      'הפסקה',
      'ריתוק',
      'טקס סיום',
      'תעודה',
      'הרצאה',
      'מצגת',
      'עבודה קבוצתית',
      'ספר מחזור',
      'צבע פנדה',
      'דבק סטיק',
      'מספריים',
      'תלבושת אחידה',
      'טיול שנתי',
      'גיר',
      'קמפוס',
      'מעונות',
      'גלובוס',
      'צלצול',
    ]),
    LocalCategory('work_office', 'מקצועות ועבודה', [
      'רופא',
      'אחות',
      'אדריכל',
      'שף',
      'מלצר',
      'טייס',
      'שוטר',
      'כבאי',
      'עורך דין',
      'מהנדס',
      'מתכנת',
      'מעצב',
      'צלם',
      'מכונאי',
      'חשמלאי',
      'שרברב',
      'נגר',
      'חקלאי',
      'רופא שיניים',
      'וטרינר',
      'ספר',
      'קופאי',
      'נהג',
      'אופה',
      'רואה חשבון',
      'פקיד קבלה',
      'עיתונאי',
      'מנהל',
      'מציל',
      'ליצן',
      'חייט',
      'בלש',
      'ספרן',
      'מנתח',
      'צבעי',
      'גנן',
      'מזכיר',
      'בריסטה',
      'משרד',
      'גננת',
      'רוקח',
      'מדען',
      'אסטרונאוט',
      'חייל',
      'מאמן',
      'פועל בניין',
      'דוור',
      'דייל אוויר',
      'מתווך',
      'מאבטח',
    ]),
    LocalCategory('technology_digital', 'טכנולוגיה ודיגיטל', [
      'טלפון חכם',
      'מחשב נייד',
      'טאבלט',
      'שעון חכם',
      'אוזניות',
      'מקלדת מחשב',
      'עכבר',
      'מסך מחשב',
      'מדפסת',
      'מצלמת רשת',
      'מטען',
      'סוללה',
      'סוללת גיבוי',
      'דיסק און קי',
      'ראוטר',
      'וויי פיי',
      'בלוטות\'',
      'נקודה חמה',
      'סיסמה',
      'זיהוי פנים',
      'צילום מסך',
      'התראה',
      'אימייל',
      'דפדפן',
      'מנוע חיפוש',
      'אתר אינטרנט',
      'אפליקציה',
      'רשת חברתית',
      'אחסון בענן',
      'גיבוי',
      'הורדה',
      'סטרימינג',
      'שיחת וידאו',
      'קוד קיו אר',
      'רובוט',
      'רחפן',
      'מציאות מדומה',
      'בינה מלאכותית',
      'צ\'אטבוט',
      'קונסולת משחקים',
      'מצלמה',
      'רמקול בלוטות\'',
      'האקר',
      'טלוויזיה חכמה',
      'קינדל',
      'ברקוד',
      'כרטיס זיכרון',
      'כבל',
      'מתאם',
      'מסך מגע',
      'סורק טביעות אצבע',
      'עוזר קולי',
      'ג\'י פי אס',
      'לוויין',
      'מדפסת תלת ממד',
    ]),
    LocalCategory('travel_vacation', 'חופשה ונסיעות', [
      'דרכון',
      'ויזה',
      'כרטיס טיסה',
      'כרטיס עלייה למטוס',
      'שדה תעופה',
      'מזוודה',
      'תיק גב',
      'מלון',
      'הוסטל',
      'ריזורט',
      'אתר קמפינג',
      'שיט תענוגות',
      'חוף ים',
      'בריכת שחייה',
      'קרם הגנה',
      'מזכרת',
      'מפה',
      'מדריך טיולים',
      'מוזיאון',
      'רוד טריפ',
      'רכבת',
      'מונית',
      'רכב שכור',
      'מעבורת',
      'רכבל',
      'שנורקלינג',
      'טיול רגלי',
      'צ\'ק אין',
      'בידוק ביטחוני',
      'גייט',
      'המראה',
      'נחיתה',
      'דיוטי פרי',
      'ג\'ט לג',
      'גלויה',
      'שק שינה',
      'שירות חדרים',
      'דלפק קבלה',
      'תג מזוודה',
      'מגבת חוף',
      'כרית נסיעות',
      'משקפת',
      'מצפן',
      'פארק שעשועים',
      'פארק מים',
    ]),
    LocalCategory('places', 'מקומות בעולם', [
      'פריז',
      'לונדון',
      'רומא',
      'ברצלונה',
      'אמסטרדם',
      'פראג',
      'וינה',
      'בודפשט',
      'ברלין',
      'אתונה',
      'ונציה',
      'ניו יורק',
      'לוס אנג\'לס',
      'מיאמי',
      'לאס וגאס',
      'טורונטו',
      'ריו דה ז\'ניירו',
      'מקסיקו סיטי',
      'טוקיו',
      'סיאול',
      'בנגקוק',
      'סינגפור',
      'הונג קונג',
      'דובאי',
      'ירושלים',
      'קהיר',
      'סידני',
      'באלי',
      'הוואי',
      'האיים המלדיביים',
      'איסלנד',
      'לפלנד',
      'מדבר סהרה',
      'יער האמזונס',
      'הגרנד קניון',
      'מפלי הניאגרה',
      'הר האוורסט',
      'האלפים השווייצריים',
      'מגדל אייפל',
      'ביג בן',
      'הקולוסיאום',
      'הפירמידות בגיזה',
      'החומה הסינית',
      'מאצ\'ו פיצ\'ו',
      'פסל החירות',
      'מדריד',
      'ליסבון',
      'דבלין',
      'קופנהגן',
      'סטוקהולם',
      'איסטנבול',
      'קייפטאון',
      'מרקש',
      'בייג\'ינג',
      'שנגחאי',
      'דלהי',
      'מומבאי',
      'פוקט',
      'סנטוריני',
      'פטרה',
    ]),
    LocalCategory('dating_relationships', 'דייטים וזוגיות', [
      'אפליקציית היכרויות',
      'מאץ\'',
      'סווייפ',
      'פרופיל',
      'הודעה',
      'מספר טלפון',
      'דייט ראשון',
      'דייט בבית קפה',
      'קראש',
      'זר פרחים',
      'דובי',
      'ולנטיינס',
      'פלירטוט',
      'מחמאה',
      'חיוך',
      'נשיקה',
      'אהבה',
      'חיבוק',
      'בן זוג',
      'זוג',
      'שיר אהבה',
      'קנאה',
      'ריב',
      'התנצלות',
      'דאבל דייט',
      'יום נישואים',
      'הצעת נישואים',
      'טבעת אירוסין',
      'חתונה',
      'פרידה',
      'בליינד דייט',
      'אקס',
      'מכתב אהבה',
      'ערב דייט',
      'ירח דבש',
    ]),
    LocalCategory('nightlife', 'לילה ומסיבות', [
      'בר',
      'פאב',
      'מועדון לילה',
      'מסיבת בית',
      'מסיבת יום הולדת',
      'להקה חיה',
      'סלקטור',
      'רשימת מוזמנים',
      'צמיד כניסה',
      'די ג\'יי',
      'רחבת ריקודים',
      'רמקול',
      'תחרות ריקודים',
      'שמפניה',
      'יין',
      'שוט',
      'ברמן',
      'אורות ניאון',
      'לייזר',
      'קונפטי',
      'כדור דיסקו',
      'סלפי',
      'ריקודים',
      'אפטר פארטי',
      'הנגאובר',
      'מועדון סטנדאפ',
      'מסיבת גג',
      'חדר בריחה',
      'ביליארד',
      'ארקייד',
      'קזינו',
      'מקלות זוהרים',
      'הזמנה למסיבה',
      'עוגת יום הולדת',
      'מתנה',
      'בלונים',
      'מסיבת תחפושות',
      'תא צילום',
      'כובע מסיבה',
      'זיקוקים',
    ]),
    LocalCategory('fashion_grooming', 'אופנה וטיפוח', [
      'חולצת טי',
      'סוודר',
      'קפוצ\'ון',
      'חולצה',
      'ג\'ינס',
      'מכנסיים',
      'מכנסיים קצרים',
      'חצאית',
      'שמלה',
      'טייץ',
      'חליפה',
      'ז\'קט',
      'מעיל',
      'מעיל גשם',
      'נעלי ספורט',
      'מגפיים',
      'סנדלים',
      'כפכפים',
      'נעלי עקב',
      'כובע',
      'משקפי שמש',
      'חגורה',
      'צעיף',
      'תיק יד',
      'שעון יד',
      'שרשרת',
      'צמיד',
      'עגילים',
      'שפתון',
      'מסקרה',
      'בושם',
      'דאודורנט',
      'תספורת',
      'מניקור',
      'תא מדידה',
      'חולצה מכופתרת',
      'חולצת פולו',
      'גופייה',
      'קרדיגן',
      'בלייזר',
      'וסט',
      'בגד ים',
      'פיג\'מה',
      'לק',
      'מייבש שיער',
    ]),
    LocalCategory('gaming', 'גיימינג', [
      'פלייסטיישן',
      'אקסבוקס',
      'נינטנדו סוויץ\'',
      'ג\'ויסטיק',
      'משחק מובייל',
      'מיינקראפט',
      'פורטנייט',
      'רובלוקס',
      'מריו',
      'פוקימון',
      'זלדה',
      'ג\'י טי איי',
      'פיפא',
      'טטריס',
      'אמונג אס',
      'שלט משחק',
      'מולטיפלייר',
      'לובי',
      'חבר לקבוצה',
      'יריב',
      'שלב',
      'בוס',
      'משימה',
      'נקודת שמירה',
      'ניקוד',
      'טבלת מובילים',
      'טורניר',
      'ניצחון',
      'הפסד',
      'משחק חוזר',
      'סקין',
      'שלל',
      'ריספאון',
      'לאג',
      'גיים אובר',
      'קול אוף דיוטי',
      'הסימס',
      'אנימל קרוסינג',
      'סוניק',
      'פקמן',
      'ליג אוף לג\'נדס',
      'ואלורנט',
      'רוקט ליג',
      'אוזניות גיימינג',
      'צ\'יט',
      'מסך מפוצל',
      'ספידראן',
      'הישג',
      'פאוור אפ',
      'מד חיים',
    ]),
    LocalCategory('music', 'מוזיקה', [
      'גיטרה',
      'פסנתר',
      'כינור',
      'תופים',
      'סקסופון',
      'חצוצרה',
      'חליל',
      'מפוחית',
      'מיקרופון',
      'זמר',
      'להקה',
      'תזמורת',
      'הופעה',
      'פסטיבל',
      'במה',
      'קהל',
      'מאחורי הקלעים',
      'אולפן הקלטות',
      'אלבום',
      'סינגל',
      'פלייליסט',
      'פזמון',
      'בית בשיר',
      'מילות שיר',
      'מנגינה',
      'קצב',
      'רמיקס',
      'קריוקי',
      'פופ',
      'רוק',
      'היפ הופ',
      'ג\'אז',
      'מוזיקה קלאסית',
      'מוזיקה אלקטרונית',
      'מוזיקת קאנטרי',
      'צ\'לו',
      'יוקולילי',
      'קלידים',
      'אקורדיון',
      'תוף מרים',
      'קסילופון',
      'קלרינט',
      'גיטרה בס',
      'מלחין',
      'מנצח',
      'כותב שירים',
      'קליפ',
      'רדיו',
      'אופרה',
      'גראמי',
    ]),
    LocalCategory('nostalgia', 'נוסטלגיה', [
      'ווקמן',
      'דיסקמן',
      'גיים בוי',
      'טמגוצ\'י',
      'טלפון נוקיה',
      'קלטת',
      'קלטת וידאו',
      'דיסקט',
      'נגן דיסקים',
      'מצלמת פילם',
      'אינטרנט בחיוג',
      'אינטרנט קפה',
      'מסנג\'ר',
      'מייספייס',
      'חלונות אקס פי',
      'אינטרנט אקספלורר',
      'ווינאמפ',
      'שולה המוקשים',
      'סוליטר',
      'ביפר',
      'טלפון קווי',
      'טלפון ציבורי',
      'ספר טלפונים',
      'טלפון חוגה',
      'מצלמה חד פעמית',
      'אלבום תמונות',
      'מכונת משחק',
      'פינבול',
      'אלבום מדבקות',
      'קלפי פוקימון',
      'פוגים',
      'גולות',
      'יו יו',
      'חבל קפיצה',
      'קלאס',
      'טלכרט',
      'משיבון',
      'מקרן שקופיות',
      'חוברת קומיקס',
      'סרטים מצוירים בשבת',
    ]),
    LocalCategory('internet_culture', 'תרבות אינטרנט', [
      'מם',
      'אימוג\'י',
      'גיף',
      'האשטאג',
      'מקל סלפי',
      'סרטון ויראלי',
      'משפיען',
      'עוקב',
      'מנוי',
      'שידור חי',
      'סטרימר',
      'פודקאסט',
      'סרטון תגובה',
      'אנבוקסינג',
      'אתגר רשת',
      'קליקבייט',
      'ספוילר',
      'טרול',
      'ספאם',
      'בוט',
      'שם משתמש',
      'תמונת פרופיל',
      'הודעה פרטית',
      'צ\'אט קבוצתי',
      'כפתור לייק',
      'אזור תגובות',
      'אלגוריתם',
      'פומו',
      'לול',
      'טרנד',
      'טיקטוק',
      'עמוד מעריצים',
      'פורום',
      'תמונה ממוזערת',
      'וי כחול',
    ]),
    LocalCategory('superheroes_fantasy', 'גיבורי על ופנטזיה', [
      'סופרמן',
      'באטמן',
      'ספיידרמן',
      'וונדר וומן',
      'איירון מן',
      'הענק הירוק',
      'תור',
      'קפטן אמריקה',
      'הפנתר השחור',
      'דדפול',
      'הג\'וקר',
      'תאנוס',
      'וולדמורט',
      'דארת\' ויידר',
      'קוסם',
      'מכשפה',
      'דרקון',
      'חד קרן',
      'בת ים',
      'ערפד',
      'איש זאב',
      'פיה',
      'שדון',
      'גובלין',
      'ענק',
      'אביר',
      'נסיכה',
      'מלך',
      'מלכה',
      'טירה',
      'צינוק',
      'שרביט קסמים',
      'כישוף',
      'שיקוי',
      'חרב',
      'מגן',
      'גלימה',
      'מסכה',
      'כוח על',
      'זהות סודית',
      'סאורון',
      'גנדלף',
      'דמבלדור',
      'ג\'יני',
      'קנטאור',
      'עוף החול',
      'עוג',
      'מפת אוצר',
      'מכונת זמן',
      'חרב אור',
    ]),
    LocalCategory('film_tv', 'קולנוע וטלוויזיה', [
      'טיטאניק',
      'אווטאר',
      'לשבור את הקרח',
      'שרק',
      'צעצוע של סיפור',
      'מלך האריות',
      'פארק היורה',
      'הארי פוטר',
      'מלחמת הכוכבים',
      'מטריקס',
      'מוצאים את נמו',
      'שכחו אותי בבית',
      'שודדי הקאריביים',
      'בחזרה לעתיד',
      'הנוקמים',
      'חברים',
      'המשרד',
      'שובר שורות',
      'משחקי הכס',
      'דברים מוזרים',
      'משחק הדיונון',
      'משפחת סימפסון',
      'בובספוג',
      'פפה פיג',
      'תוכנית ריאליטי',
      'שעשועון',
      'תוכנית אירוח',
      'סרט תיעודי',
      'קומדיה',
      'אימה',
      'סרט פעולה',
      'אנימציה',
      'במאי',
      'שחקן',
      'נבל',
      'תפנית בעלילה',
      'טריילר',
      'כרטיס קולנוע',
      'בית קולנוע',
      'שירות סטרימינג',
      'מלתעות',
      'אי טי',
      'רוקי',
      'מכסחי השדים',
      'גברים בשחור',
      'הסנדק',
      'ספרות זולה',
      'פורסט גאמפ',
      'ג\'ומנג\'י',
      'קראטה קיד',
      'גנוב על הירח',
      'המיניונים',
      'מואנה',
      'אנקאנטו',
      'הכתר',
      'מראה שחורה',
      'בית הנייר',
      'ונסדיי',
      'כוכב קולנוע',
      'כתוביות',
    ]),
    LocalCategory('sports', 'ספורט וכושר', [
      'כדורגל',
      'כדורסל',
      'כדורעף',
      'בייסבול',
      'רוגבי',
      'הוקי',
      'טניס',
      'פאדל',
      'פינג פונג',
      'בדמינטון',
      'סקווש',
      'אגרוף',
      'ג\'ודו',
      'קראטה',
      'היאבקות',
      'שחייה',
      'גלישה',
      'חתירה',
      'קיאקים',
      'צלילה',
      'ריצה',
      'רכיבה על אופניים',
      'מרתון',
      'טריאתלון',
      'התעמלות',
      'הרמת משקולות',
      'הליכון',
      'משקולת יד',
      'מוט משקולות',
      'סקוואט',
      'שכיבות סמיכה',
      'מתח',
      'פלאנק',
      'סקי',
      'סנובורד',
      'החלקה על הקרח',
      'גולף',
      'קליעה בחצים',
      'באולינג',
      'קשתות',
      'שופט',
      'לוח תוצאות',
      'מדליה',
      'גביע',
      'פודיום',
      'כדוריד',
      'קריקט',
      'פוטבול אמריקאי',
      'לקרוס',
      'טאקוונדו',
      'סיף',
      'שיט מפרשיות',
      'קאנו',
      'טיפוס צוקים',
      'רכיבה על סקייטבורד',
      'יוגה',
      'פילאטיס',
      'קטלבל',
      'גומיית התנגדות',
      'משרוקית',
    ]),
    LocalCategory('nature_weather', 'טבע ומזג אוויר', [
      'שמש',
      'ירח',
      'כוכב',
      'קשת בענן',
      'ענן',
      'גשם',
      'שלג',
      'רעם',
      'ברק',
      'רוח',
      'טורנדו',
      'הוריקן',
      'הר געש',
      'רעידת אדמה',
      'הר',
      'עמק',
      'נהר',
      'אגם',
      'מפל',
      'אוקיינוס',
      'אי',
      'מדבר',
      'יער',
      'ג\'ונגל',
      'מערה',
      'קניון',
      'קרחון',
      'צוק',
      'אחו',
      'עץ',
      'פרח',
      'ורד',
      'חמנייה',
      'קקטוס',
      'פטרייה',
      'עלה',
      'אצטרובל',
      'חלוק נחל',
      'חול',
      'שונית אלמוגים',
      'גל',
      'שקיעה',
      'זריחה',
      'זוהר צפוני',
      'מים',
    ]),
    LocalCategory('transportation', 'כלי תחבורה', [
      'מכונית',
      'אוטובוס',
      'מטוס',
      'מסוק',
      'אופניים',
      'אופנוע',
      'קורקינט',
      'משאית',
      'ואן',
      'אמבולנס',
      'כבאית',
      'ניידת משטרה',
      'חשמלית',
      'רכבת תחתית',
      'רכבת מהירה',
      'סירה',
      'ספינה',
      'יאכטה',
      'סירת מפרש',
      'אופנוע ים',
      'כדור פורח',
      'גונדולה',
      'ריקשה',
      'טוק טוק',
      'לימוזינה',
      'קרוואן',
      'טרקטור',
      'דחפור',
      'מלגזה',
      'סקייטבורד',
      'גלגיליות',
      'כיסא גלגלים',
      'עגלת תינוק',
      'מעלית',
      'מדרגות נעות',
    ]),
    LocalCategory('hobbies_free_time', 'תחביבים ופנאי', [
      'קריאה',
      'בישול',
      'אפייה',
      'גינון',
      'ציור',
      'רישום',
      'צילום',
      'סריגה',
      'תפירה',
      'דיג',
      'קמפינג',
      'שיעורי ריקוד',
      'שירה',
      'שחמט',
      'פאזלים',
      'אספנות',
      'צפרות',
      'צפייה בכוכבים',
      'קדרות',
      'נגרות',
      'אוריגמי',
      'קליגרפיה',
      'סקראפבוקינג',
      'כתיבת יומן',
      'מדיטציה',
      'קסמים',
      'בניית דגמים',
      'איסוף מטבעות',
      'איסוף בולים',
      'משחקי קופסה',
      'משחקי קלפים',
      'תשבצים',
      'סודוקו',
      'משחק בתיאטרון',
      'לגו',
      'ולוגינג',
      'התנדבות',
      'לימוד שפות',
      'עפיפון',
      'פיקניק',
    ]),
    LocalCategory('israeli_slang', 'סלנג ישראלי', [
      'סבבה',
      'אחלה',
      'וואלה',
      'תכלס',
      'יאללה',
      'פגז',
      'אש',
      'חבל"ז',
      'קטלני',
      'מטורף',
      'אחי',
      'גבר',
      'נשמה',
      'כפרה',
      'חופר',
      'כבד',
      'נודניק',
      'קרציה',
      'סחי',
      'סטלן',
      'צ\'יל',
      'זורם',
      'מבסוט',
      'סתלבט',
      'פדיחה',
      'פשלה',
      'באסה',
      'נדפק',
      'בושות',
      'חרטה',
      'בלוף',
      'קומבינה',
      'פראייר',
      'הזוי',
      'להבריז',
      'לייבש',
      'להתפלח',
      'לפרגן',
      'להתקמבן',
      'קריזה',
      'ג\'ננה',
      'שבוז',
      'מורעל',
      'לחוץ',
      'קרינג\'',
      'פלקס',
      'גוסטינג',
      'רואסט',
      'וייב',
    ]),
    LocalCategory('idf_service', 'צה"ל ושירות', [
      'צו ראשון',
      'גיוס',
      'בקו"ם',
      'שרשרת חיול',
      'חוגר',
      'מדים',
      'דיסקית',
      'כומתה',
      'קיטבג',
      'נעליים צבאיות',
      'טירונות',
      'מסדר',
      'מטווח',
      'מסע',
      'תרגיל',
      'מפקד',
      'מ"מ',
      'מ"פ',
      'רס"ר',
      'רס"פ',
      'שמירה',
      'תורנות',
      'מטבח',
      'ניקיון',
      'שק"ם',
      'אפטר',
      'חמשוש',
      'רגילה',
      'גימלים',
      'יציאה',
      'מחבוש',
      'משפט',
      'דיגום',
      'נפקדות',
      'פז"ם',
      'צעיר',
      'ותיק',
      'קרבי',
      'ג\'ובניק',
      'בסיס פתוח',
      'בסיס סגור',
      'מילואים',
      'ת"ש',
      'קב"ן',
      'מש"קית ת"ש',
      'קצין מיון',
      'שחרור',
    ]),
  ],
};

/// A language's categories; an unknown one gets "he"'s.
List<LocalCategory> localCategoriesFor(String language) =>
    localContent[language] ?? localContent['he']!;

// Alternate spellings accepted only for the impostor's final guess, in
// every language.
const localGuessAliases = <String, List<String>>{
  'Hot dog': ['Hotdog'],
  'Omelette': ['Omelet'],
  'French fries': ['Fries', 'Chips'],
  'Donut': ['Doughnut'],
  'Air conditioner': ['AC', 'Aircon'],
  'Trash can': ['Bin', 'Garbage can'],
  'Cafeteria': ['Canteen'],
  'Detective': ['Résumé', 'CV'],
  'Smartphone': ['Smart phone', 'Mobile phone', 'Cell phone'],
  'USB drive': ['Flash drive', 'Thumb drive'],
  'WiFi': ['Wi-Fi'],
  'Backpack': ['Rucksack'],
  'Hoodie': ['Hoody'],
  'Trousers': ['Pants'],
  'Sneakers': ['Trainers'],
  'Pokémon': ['Pokemon'],
  'Hip hop': ['Hip-hop'],
  'Spider Man': ['Spider-Man', 'Spiderman'],
  'Movie theater': ['Cinema', 'Movie theatre'],
  'Football': ['Soccer'],
  'Table tennis': ['Ping pong'],
  'Push up': ['Push-up', 'Pushup', 'Press-up'],
  'Pull up': ['Pull-up', 'Pullup'],
  'נקניקייה': ['נקניקיה'],
  'צ\'יפס': ['ציפס'],
  'במבה': ['נאצוס', 'Bamba'],
  'שקשוקה': ['גואקמולי'],
  'שניצל': ['Schnitzel'],
  'ג\'ירפה': ['גירפה'],
  'אייר פרייר': ['איירפרייר', 'Air Fryer'],
  'בריסטה': ['Barista'],
  'וויי פיי': ['וייפיי', 'וויפי', 'ווייפיי', 'WiFi', 'Wi-Fi'],
  'בלוטות\'': ['בלוטוס', 'Bluetooth'],
  'נקודה חמה': ['הוטספוט', 'Hotspot', 'Hot Spot'],
  'צ\'אטבוט': ['צ\'אט בוט', 'Chatbot', 'Chat Bot'],
  'האקר': ['Hacker'],
  'קינדל': ['Kindle'],
  'רוד טריפ': ['Road trip'],
  'גייט': ['Gate'],
  'דיוטי פרי': ['Duty free', 'דיוטיפרי'],
  'ג\'ט לג': ['ג\'טלג', 'Jet Lag'],
  'ולנטיינס': ['Valentines', 'ולנטיין'],
  'אקס': ['Ex'],
  'די ג\'יי': ['דיג\'יי', 'DJ'],
  'מועדון סטנדאפ': ['מועדון סטנד אפ'],
  'פלייסטיישן': ['פלייסטישן', 'PlayStation'],
  'אקסבוקס': ['Xbox'],
  'נינטנדו סוויץ\'': ['Nintendo Switch'],
  'ג\'ויסטיק': ['Joystick'],
  'מיינקראפט': ['Minecraft'],
  'פורטנייט': ['Fortnite'],
  'רובלוקס': ['Roblox'],
  'פוקימון': ['Pokemon', 'Pokémon'],
  'פיפא': ['FIFA'],
  'טטריס': ['Tetris'],
  'אמונג אס': ['Among Us'],
  'מולטיפלייר': ['Multiplayer'],
  'נקודת שמירה': ['צ\'קפוינט', 'Checkpoint'],
  'טבלת מובילים': ['לידרבורד'],
  'משחק חוזר': ['רימאץ\'', 'Rematch'],
  'ריספאון': ['Respawn'],
  'פקמן': ['פאקמן', 'Pac-Man', 'Pacman'],
  'ואלורנט': ['Valorant'],
  'פאוור אפ': ['Power up', 'Powerup'],
  'היפ הופ': ['היפהופ', 'Hip Hop'],
  'גראמי': ['Grammy'],
  'גיים בוי': ['גיימבוי', 'Game Boy'],
  'מייספייס': ['מיי ספייס', 'MySpace'],
  'אינטרנט אקספלורר': ['אקספלורר', 'Internet Explorer'],
  'ווינאמפ': ['וינאמפ', 'Winamp'],
  'טיקטוק': ['TikTok'],
  'ספיידרמן': ['ספיידר מן'],
  'וונדר וומן': ['וונדרוומן'],
  'איירון מן': ['איירונמן'],
  'כדורגל': ['סוקר'],
  'פינג פונג': ['טניס שולחן'],
  'פוטבול אמריקאי': ['פוטבול'],
  'לגו': ['Lego'],
};
