// GENERATED FILE — DO NOT EDIT.
//
// The words the one-device game draws on. Generated from
// server/internal/content by "go run ./cmd/exportwords", because a game with
// no server still needs them on the device, and a second hand-written list is
// a list that drifts. The Go test guarding this fails if the two fall out of
// step.

/// A category and the words it can produce.
class LocalCategory {
  const LocalCategory(this.id, this.name, this.words);

  final String id;
  final String name;
  final List<String> words;
}

const localCategories = <LocalCategory>[
  LocalCategory('food', 'אוכל', [
    'פיצה',
    'פלאפל',
    'שווארמה',
    'המבורגר',
    'סושי',
    'פסטה',
    'חומוס',
    'שניצל',
    'פנקייק',
    'קוסקוס',
    'מרק',
    'גלידה',
    'שוקולד',
    'אבטיח',
    'בננה',
    'תות',
    'פופקורן',
    'סלט',
    'בורקס',
    'עוגה',
  ]),
  LocalCategory('animals', 'חיות', [
    'כלב',
    'חתול',
    'אריה',
    'נמר',
    'פיל',
    'ג\'ירפה',
    'קוף',
    'דולפין',
    'כריש',
    'תנין',
    'זברה',
    'פינגווין',
    'סוס',
    'תרנגול',
    'כבשה',
    'עז',
    'שועל',
    'דוב',
    'צב',
    'תוכי',
  ]),
  LocalCategory('sports', 'ספורט', [
    'כדורגל',
    'כדורסל',
    'כדורעף',
    'טניס',
    'שחייה',
    'ריצה',
    'אגרוף',
    'ג\'ודו',
    'גלישה',
    'סקי',
    'סנוקר',
    'באולינג',
    'התעמלות',
    'קראטה',
    'היאבקות',
    'פינגפונג',
    'הוקי',
    'פוטבול',
    'בייסבול',
    'רכיבה',
  ]),
  LocalCategory('professions', 'מקצועות', [
    'רופא',
    'מורה',
    'שוטר',
    'כבאי',
    'טבח',
    'נהג',
    'טייס',
    'עיתונאי',
    'צלם',
    'מהנדס',
    'נגר',
    'חשמלאי',
    'אדריכל',
    'חקלאי',
    'רוקח',
    'זמר',
    'וטרינר',
    'בלש',
    'מדען',
    'שף',
  ]),
  LocalCategory('places', 'מקומות', [
    'חוף',
    'מדבר',
    'יער',
    'מערה',
    'שוק',
    'פארק',
    'קניון',
    'מוזיאון',
    'ספרייה',
    'מסעדה',
    'אצטדיון',
    'טירה',
    'ארמון',
    'נמל',
    'אוניברסיטה',
    'מלון',
    'בריכה',
    'קולנוע',
    'כלא',
    'שדה',
  ]),
  LocalCategory('objects', 'חפצים', [
    'מטרייה',
    'מפתח',
    'שעון',
    'טלפון',
    'מצלמה',
    'משקפיים',
    'תיק',
    'כרית',
    'כיסא',
    'שולחן',
    'מנורה',
    'מחשב',
    'אוזניות',
    'מראה',
    'בקבוק',
    'מגבת',
    'פנס',
    'סולם',
    'מזוודה',
    'שלט',
  ]),
];
