// GENERATED FILE — DO NOT EDIT.
//
// The words the one-device game draws on. Generated from
// server/internal/content by "go run ./cmd/exportwords", because a game with
// no server still needs them on the device, and a second hand-written list is
// a list that drifts. The Go test guarding this fails if the two fall out of
// step.

/// A category and the words it can produce.
class LocalCategory {
  const LocalCategory(this.id, this.name, this.words);

  final String id;
  final String name;
  final List<String> words;
}

/// Each language's categories, by language code
/// (server/internal/content/languages/<code>.json).
const localContent = <String, List<LocalCategory>>{
  'en': [
    LocalCategory('food', 'Food & Drink', [
      'Falafel',
      'Shawarma',
      'Taco',
      'Burrito',
      'Hot dog',
      'Pizza',
      'Focaccia',
      'Lasagna',
      'Pasta',
      'Gnocchi',
      'Sushi',
      'Ramen',
      'Pad Thai',
      'Dim sum',
      'Curry',
      'Pancake',
      'Waffle',
      'Cereal',
      'Omelette',
      'Bagel',
      'Croissant',
      'Muffin',
      'Toast',
      'Pretzel',
      'Donut',
      'Tiramisu',
      'Brownie',
      'Cheesecake',
      'Cupcake',
      'Ice cream',
      'Popcorn',
      'Nachos',
      'Chips',
      'Crackers',
      'Peanuts',
      'Hummus',
      'Ketchup',
      'Mayo',
      'Guacamole',
      'Mustard',
      'Espresso',
      'Cappuccino',
      'Latte',
      'Tea',
      'Hot chocolate',
      'Lemonade',
      'Cola',
      'Soda',
      'Smoothie',
      'Milkshake',
    ]),
    LocalCategory('home', 'At Home', [
      'Fridge',
      'Freezer',
      'Oven',
      'Microwave',
      'Dishwasher',
      'Kettle',
      'Toaster',
      'Blender',
      'Coffee maker',
      'Air fryer',
      'Vacuum',
      'Broom',
      'Mop',
      'Bucket',
      'Rag',
      'Washing machine',
      'Dryer',
      'Laundry basket',
      'Iron',
      'Clothesline',
      'Sofa',
      'Armchair',
      'Table',
      'Chair',
      'Cabinet',
      'Bed',
      'Pillow',
      'Blanket',
      'Mattress',
      'Dresser',
      'Shower',
      'Bathtub',
      'Sink',
      'Mirror',
      'Toilet',
      'Closet',
      'Drawer',
      'Shelf',
      'Door',
      'Key',
      'Air conditioner',
      'Fan',
      'Heater',
      'Curtain',
      'Rug',
      'Doorbell',
      'Intercom',
      'Mailbox',
      'Window',
      'Blinds',
    ]),
    LocalCategory('school_students', 'School & College', [
      'Pencil',
      'Pen',
      'Eraser',
      'Sharpener',
      'Highlighter',
      'Notebook',
      'Binder',
      'Folder',
      'Textbook',
      'Planner',
      'Whiteboard',
      'Projector',
      'Desk',
      'Chair',
      'Map',
      'Exam',
      'Quiz',
      'Essay',
      'Grade',
      'Report card',
      'Bell',
      'Recess',
      'Free period',
      'Homework',
      'Detention',
      'Teacher',
      'Principal',
      'Office',
      'Library',
      'Cafeteria',
      'Finals',
      'Mock exam',
      'Class trip',
      'Prom',
      'Yearbook',
      'Lecture',
      'Tutorial',
      'Semester',
      'Course',
      'Degree',
      'Summary',
      'Presentation',
      'Project',
      'Deadline',
      'Submission',
      'Appeal',
      'Curve',
      'Cheating',
      'Cramming',
      'Retake',
    ]),
    LocalCategory('work_office', 'Work & Office', [
      'Email',
      'Slack',
      'Teams',
      'Zoom',
      'Phone call',
      'Meeting',
      'Agenda',
      'Slides',
      'Minutes',
      'Conference room',
      'Task',
      'Ticket',
      'Project',
      'Deadline',
      'Priority',
      'Sprint',
      'Standup',
      'Retro',
      'Backlog',
      'Demo',
      'Excel',
      'Word doc',
      'File',
      'Spreadsheet',
      'Report',
      'Printer',
      'Scanner',
      'Stapler',
      'Whiteboard',
      'Marker',
      'Manager',
      'New hire',
      'Recruiter',
      'Client',
      'Supplier',
      'Interview',
      'Resume',
      'Promotion',
      'Raise',
      'Bonus',
      'Office',
      'Remote work',
      'Hybrid',
      'Day off',
      'Sick day',
      'Kitchenette',
      'Coffee machine',
      'Lunch',
      'Gossip',
      'Happy hour',
    ]),
    LocalCategory('technology_digital', 'Tech & Digital', [
      'Smartphone',
      'Tablet',
      'Laptop',
      'Smartwatch',
      'Headphones',
      'WiFi',
      'Bluetooth',
      'Router',
      'Hotspot',
      'AirDrop',
      'Charger',
      'Cable',
      'Battery',
      'Adapter',
      'Power bank',
      'Camera',
      'Face ID',
      'Flashlight',
      'Notification',
      'Screenshot',
      'WhatsApp',
      'Telegram',
      'Instagram',
      'TikTok',
      'Discord',
      'Browser',
      'Google',
      'Search',
      'Tabs',
      'Cookies',
      'Password',
      'Code',
      'Encryption',
      'Firewall',
      'Antivirus',
      'Cloud',
      'Backup',
      'Storage',
      'Sync',
      'Download',
      'Algorithm',
      'Prompt',
      'Chatbot',
      'Image generator',
      'Voice assistant',
      'GitHub',
      'Docker',
      'Interface',
      'Server',
      'Database',
    ]),
    LocalCategory('travel_vacation', 'Travel & Vacation', [
      'Passport',
      'Plane ticket',
      'Boarding pass',
      'Visa',
      'Travel insurance',
      'Check in',
      'Gate',
      'Security',
      'Duty free',
      'Baggage claim',
      'Takeoff',
      'Landing',
      'Connection',
      'Delay',
      'Jet lag',
      'Suitcase',
      'Carry on',
      'Backpack',
      'Luggage tag',
      'Overweight',
      'Hotel',
      'Hostel',
      'Apartment',
      'Camping',
      'Resort',
      'Reception',
      'Lobby',
      'Room key',
      'Breakfast',
      'Room service',
      'Beach',
      'Pool',
      'Umbrella',
      'Towel',
      'Sunscreen',
      'Map',
      'Tour guide',
      'Museum',
      'Viewpoint',
      'Souvenir',
      'Booking',
      'Vacation rental',
      'Reservation',
      'Review',
      'Cancellation',
      'Cruise',
      'Cable car',
      'Skiing',
      'Hiking',
      'Road trip',
    ]),
    LocalCategory('places', 'Places Around the World', [
      'Paris',
      'London',
      'Rome',
      'Barcelona',
      'Amsterdam',
      'Prague',
      'Vienna',
      'Budapest',
      'Berlin',
      'Krakow',
      'Santorini',
      'Mykonos',
      'Ibiza',
      'Malta',
      'Cyprus',
      'Tokyo',
      'Seoul',
      'Bangkok',
      'Singapore',
      'Hong Kong',
      'New York',
      'Los Angeles',
      'Miami',
      'Las Vegas',
      'Toronto',
      'Maldives',
      'Bali',
      'Hawaii',
      'Phuket',
      'Seychelles',
      'Grand Canyon',
      'Niagara Falls',
      'Sahara',
      'Amazon',
      'Fjords',
      'Colosseum',
      'Pyramids',
      'Machu Picchu',
      'Acropolis',
      'Petra',
      'Eiffel Tower',
      'Big Ben',
      'Times Square',
      'Burj Khalifa',
      'Sagrada Familia',
      'Everest',
      'Dolomites',
      'Iceland',
      'Patagonia',
      'Lapland',
    ]),
    LocalCategory('dating_relationships', 'Dating & Relationships', [
      'Match',
      'Swipe',
      'Profile',
      'Bio',
      'Photo',
      'Message',
      'Like',
      'Reply',
      'DM',
      'Phone number',
      'Coffee shop',
      'Bar',
      'Restaurant',
      'Cinema',
      'Walk',
      'Crush',
      'Chemistry',
      'Butterflies',
      'Attraction',
      'Love',
      'Compliment',
      'Look',
      'Smile',
      'Touch',
      'Kiss',
      'Ghosting',
      'Breadcrumbing',
      'Double text',
      'Blocking',
      'Benching',
      'Trust',
      'Jealousy',
      'Argument',
      'Apology',
      'Compromise',
      'First date',
      'Friendship',
      'Friend zone',
      'Ex',
      'Comeback',
      'Meeting parents',
      'Moving in',
      'Proposal',
      'Ring',
      'Wedding',
      'Lie',
      'Secret',
      'Suspicion',
      'Excuse',
      'Red flag',
    ]),
    LocalCategory('nightlife', 'Nightlife & Going Out', [
      'Bar',
      'Pub',
      'Club',
      'Karaoke',
      'House party',
      'Line',
      'Bouncer',
      'Guest list',
      'Wristband',
      'Reservation',
      'DJ',
      'Dance floor',
      'Speaker',
      'Bass',
      'Playlist',
      'Glass',
      'Bottle',
      'Cocktail',
      'Beer',
      'Shot',
      'Neon',
      'Laser',
      'Smoke',
      'Confetti',
      'Flash',
      'Dancing',
      'Selfie',
      'Flirting',
      'Laughing',
      'Meeting people',
      'Taxi',
      'Pizza',
      'Afterparty',
      'Sunrise',
      'Hangover',
      'Birthday',
      'Bachelor party',
      'Bachelorette party',
      'Festival',
      'Rooftop party',
      'Billiards',
      'Bowling',
      'Arcade',
      'Comedy club',
      'Casino',
      'Bill',
      'Tip',
      'Ride home',
      'Phone charger',
      'Water',
    ]),
    LocalCategory('weddings_events', 'Weddings & Parties', [
      'Proposal',
      'Engagement',
      'Wedding date',
      'Invitation',
      'Fiance',
      'Ceremony',
      'Vows',
      'Officiant',
      'Wedding ring',
      'Aisle',
      'Bride',
      'Groom',
      'Wedding dress',
      'Suit',
      'Veil',
      'Flowers',
      'Candles',
      'Balloons',
      'Confetti',
      'Centerpiece',
      'Venue',
      'Garden',
      'Reception',
      'Dance floor',
      'Bar',
      'Catering',
      'Buffet',
      'Main course',
      'Dessert',
      'Wedding cake',
      'Photographer',
      'Videographer',
      'Photo booth',
      'Album',
      'Slideshow',
      'DJ',
      'First dance',
      'Slow dance',
      'Playlist',
      'Band',
      'Gift',
      'Card',
      'Toast',
      'Speech',
      'Seating chart',
      'Baby shower',
      'Birthday party',
      'Anniversary',
      'Graduation',
      'Bachelor party',
    ]),
    LocalCategory('fashion_grooming', 'Fashion & Grooming', [
      'Tank top',
      'Sweater',
      'Hoodie',
      'Blouse',
      'Polo shirt',
      'Jeans',
      'Pants',
      'Shorts',
      'Skirt',
      'Leggings',
      'Coat',
      'Jacket',
      'Blazer',
      'Vest',
      'Raincoat',
      'Sneakers',
      'Heels',
      'Boots',
      'Sandals',
      'Flip flops',
      'Hat',
      'Sunglasses',
      'Belt',
      'Scarf',
      'Bag',
      'Watch',
      'Necklace',
      'Bracelet',
      'Ring',
      'Earrings',
      'Foundation',
      'Lipstick',
      'Mascara',
      'Blush',
      'Eyeliner',
      'Haircut',
      'Blow dry',
      'Straightener',
      'Beard',
      'Shaving',
      'Nail polish',
      'Manicure',
      'Cream',
      'Perfume',
      'Deodorant',
      'Size',
      'Brand',
      'Sale',
      'Collection',
      'Fitting room',
    ]),
    LocalCategory('gaming', 'Gaming', [
      'PlayStation',
      'Xbox',
      'Switch',
      'PC',
      'Mobile',
      'Shooter',
      'Racing',
      'Strategy',
      'Survival',
      'Puzzle',
      'Lobby',
      'Clan',
      'Party',
      'Match',
      'Rank',
      'Frames',
      'Ping',
      'Lag',
      'Server',
      'Graphics',
      'Loot',
      'Spawn',
      'Respawn',
      'Camping',
      'Grinding',
      'Level',
      'Boss',
      'Quest',
      'Experience',
      'Skill',
      'Skin',
      'Character',
      'Weapon',
      'Emote',
      'Battle pass',
      'DLC',
      'Expansion',
      'Coins',
      'Store',
      'Microtransaction',
      'Lives',
      'Checkpoint',
      'Save',
      'Game over',
      'Score',
      'Tournament',
      'Leaderboard',
      'Victory',
      'Defeat',
      'Rematch',
    ]),
    LocalCategory('music', 'Music', [
      'Guitar',
      'Bass guitar',
      'Violin',
      'Cello',
      'Ukulele',
      'Piano',
      'Keyboard',
      'Organ',
      'Synthesizer',
      'Accordion',
      'Drums',
      'Tambourine',
      'Triangle',
      'Bongos',
      'Xylophone',
      'Saxophone',
      'Trumpet',
      'Flute',
      'Clarinet',
      'Harmonica',
      'Stage',
      'Microphone',
      'Audience',
      'Encore',
      'Backstage',
      'Studio',
      'Headphones',
      'Mixer',
      'Recording',
      'Autotune',
      'Chorus',
      'Verse',
      'Intro',
      'Bridge',
      'Solo',
      'Album',
      'Single',
      'Playlist',
      'Remix',
      'Cover',
      'Pop',
      'Rock',
      'Hip hop',
      'Techno',
      'Jazz',
      'DJ',
      'Karaoke',
      'Festival',
      'Concert',
      'Party',
    ]),
    LocalCategory('nostalgia', 'Nostalgia', [
      'Walkman',
      'Discman',
      'Game Boy',
      'Nokia',
      'Tamagotchi',
      'Cassette',
      'VHS',
      'Floppy disk',
      'CD',
      'Film roll',
      'ICQ',
      'MSN Messenger',
      'Dial up',
      'MySpace',
      'Internet Explorer',
      'Windows XP',
      'Winamp',
      'Minesweeper',
      'Solitaire',
      'Paint',
      'Ringtone',
      'Text message',
      'Snake',
      'Pager',
      'Answering machine',
      'Pogs',
      'Marbles',
      'Yoyo',
      'Sticker album',
      'Pokemon cards',
      'Pac Man',
      'Tetris',
      'Space Invaders',
      'Pinball',
      'Donkey Kong',
      'Hopscotch',
      'Jump rope',
      'Tag',
      'Jacks',
      'Marco Polo',
      'Landline',
      'Payphone',
      'Phone card',
      'Phone book',
      'Rotary phone',
      'Polaroid',
      'Disposable camera',
      'Photo album',
      'Slide projector',
      'Darkroom',
    ]),
    LocalCategory('internet_slang', 'Internet Slang', [
      'LOL',
      'OMG',
      'LMAO',
      'Facepalm',
      'Mind blown',
      'Slay',
      'Goat',
      'Fire',
      'Lit',
      'Iconic',
      'Vibe',
      'Mood',
      'Chill',
      'Salty',
      'Extra',
      'Cringe',
      'Sus',
      'Toxic',
      'Basic',
      'Mid',
      'Flex',
      'Drip',
      'Clout',
      'Glow up',
      'Main character',
      'Viral',
      'Trending',
      'Hashtag',
      'Influencer',
      'Follower',
      'Crush',
      'Bae',
      'Situationship',
      'Ghosted',
      'Simp',
      'Meme',
      'Troll',
      'Noob',
      'Spam',
      'Bot',
      'BRB',
      'IDK',
      'FOMO',
      'TMI',
      'DM',
      'No cap',
      'Bet',
      'Lowkey',
      'Highkey',
      'Vibe check',
    ]),
    LocalCategory('superheroes_fantasy', 'Superheroes & Fantasy', [
      'Superman',
      'Batman',
      'Spider Man',
      'Wonder Woman',
      'Iron Man',
      'Flying',
      'Invisibility',
      'Super strength',
      'Telepathy',
      'Teleportation',
      'Joker',
      'Thanos',
      'Voldemort',
      'Darth Vader',
      'Sauron',
      'Cape',
      'Mask',
      'Shield',
      'Hammer',
      'Costume',
      'Wizard',
      'Witch',
      'Wand',
      'Spell',
      'Potion',
      'Dragon',
      'Unicorn',
      'Troll',
      'Elf',
      'Goblin',
      'Castle',
      'Kingdom',
      'Dungeon',
      'Portal',
      'Tower',
      'Knight',
      'Princess',
      'King',
      'Queen',
      'Prince',
      'Robot',
      'Alien',
      'Spaceship',
      'Time machine',
      'Lightsaber',
      'Avengers',
      'Justice League',
      'X Men',
      'Sidekick',
      'Secret identity',
    ]),
    LocalCategory('film_tv', 'Movies & TV', [
      'Movie',
      'Series',
      'Episode',
      'Season',
      'Special',
      'Comedy',
      'Drama',
      'Horror',
      'Action',
      'Thriller',
      'Director',
      'Screenwriter',
      'Producer',
      'Actor',
      'Extra',
      'Camera',
      'Lighting',
      'Microphone',
      'Set design',
      'Makeup',
      'Hero',
      'Villain',
      'Character',
      'Plot twist',
      'Ending',
      'Trailer',
      'Spoiler',
      'Subtitles',
      'Dubbing',
      'Credits',
      'Sequel',
      'Prequel',
      'Remake',
      'Spinoff',
      'Trilogy',
      'Reality show',
      'Game show',
      'News',
      'Talk show',
      'Documentary',
      'Netflix',
      'Disney',
      'YouTube',
      'Amazon Prime',
      'HBO',
      'Popcorn',
      'Ticket',
      'Theater',
      'Screen',
      'Seat',
    ]),
    LocalCategory('sports', 'Sports & Fitness', [
      'Soccer',
      'Basketball',
      'Volleyball',
      'Handball',
      'Hockey',
      'Tennis',
      'Padel',
      'Ping pong',
      'Badminton',
      'Squash',
      'Boxing',
      'Judo',
      'Karate',
      'Taekwondo',
      'Wrestling',
      'Swimming',
      'Surfing',
      'Rowing',
      'Kayaking',
      'Diving',
      'Running',
      'Cycling',
      'Marathon',
      'Triathlon',
      'Race walking',
      'Treadmill',
      'Dumbbell',
      'Barbell',
      'Kettlebell',
      'Resistance band',
      'Squat',
      'Deadlift',
      'Bench press',
      'Pull up',
      'Plank',
      'Skiing',
      'Snowboarding',
      'Figure skating',
      'Sledding',
      'Curling',
      'Golf',
      'Darts',
      'Bowling',
      'Billiards',
      'Archery',
      'Referee',
      'Whistle',
      'Scoreboard',
      'Medal',
      'Podium',
    ]),
  ],
  'he': [
    LocalCategory('food', 'אוכל ושתייה', [
      'פלאפל',
      'שווארמה',
      'סביח',
      'טאקו',
      'בוריטו',
      'פיצה',
      'פוקאצ\'ה',
      'לזניה',
      'פסטה',
      'ניוקי',
      'סושי',
      'ראמן',
      'פאד תאי',
      'דים סאם',
      'קארי',
      'שקשוקה',
      'פנקייק',
      'וופל',
      'קורנפלקס',
      'חביתה',
      'בורקס',
      'קרואסון',
      'בייגל',
      'לחמנייה',
      'טוסט',
      'טירמיסו',
      'בראוניז',
      'עוגת גבינה',
      'דונאט',
      'גלידה',
      'פופקורן',
      'נאצ\'וס',
      'בייגלה',
      'צ\'יפס',
      'קרקרים',
      'חומוס',
      'טחינה',
      'גוואקמולי',
      'קטשופ',
      'מיונז',
      'אספרסו',
      'קפוצ\'ינו',
      'לאטה',
      'תה',
      'שוקו',
      'לימונדה',
      'קולה',
      'סודה',
      'שייק',
      'מילקשייק',
    ]),
    LocalCategory('home', 'בבית', [
      'מקרר',
      'מקפיא',
      'תנור',
      'מיקרוגל',
      'מדיח',
      'קומקום',
      'טוסטר',
      'בלנדר',
      'מכונת קפה',
      'אייר פרייר',
      'שואב אבק',
      'מטאטא',
      'מגב',
      'דלי',
      'סמרטוט',
      'מכונת כביסה',
      'מייבש',
      'סל כביסה',
      'מגהץ',
      'מתלה כביסה',
      'ספה',
      'כורסה',
      'שולחן',
      'כיסא',
      'מזנון',
      'מיטה',
      'כרית',
      'שמיכה',
      'מזרן',
      'שידה',
      'מקלחת',
      'אמבטיה',
      'כיור',
      'מראה',
      'אסלה',
      'ארון',
      'מגירה',
      'מדף',
      'דלת',
      'מפתח',
      'מזגן',
      'מאוורר',
      'רדיאטור',
      'וילון',
      'שטיח',
      'פעמון',
      'אינטרקום',
      'תיבת דואר',
      'תריס',
      'חלון',
    ]),
    LocalCategory('school_students', 'בית ספר וסטודנטים', [
      'עיפרון',
      'עט',
      'מחק',
      'מחדד',
      'מרקר',
      'מחברת',
      'קלסר',
      'דפדפת',
      'ספר לימוד',
      'יומן',
      'לוח',
      'מקרן',
      'שולחן',
      'כיסא',
      'מפה',
      'מבחן',
      'בוחן',
      'עבודה',
      'ציון',
      'תעודה',
      'צלצול',
      'הפסקה',
      'שיעור חופשי',
      'שיעורי בית',
      'תורנות',
      'מורה',
      'מנהל',
      'מזכירות',
      'ספרייה',
      'קפיטריה',
      'בגרות',
      'מתכונת',
      'הקבצה',
      'מגמה',
      'טיול שנתי',
      'הרצאה',
      'תרגול',
      'סמסטר',
      'קורס',
      'תואר',
      'סיכום',
      'מצגת',
      'פרויקט',
      'דדליין',
      'הגשה',
      'מועד א\'',
      'ערעור',
      'פקטור',
      'העתקה',
      'חרישה',
    ]),
    LocalCategory('work_office', 'עבודה ומשרד', [
      'מייל',
      'סלאק',
      'טימס',
      'זום',
      'שיחת טלפון',
      'ישיבה',
      'אג\'נדה',
      'מצגת',
      'פרוטוקול',
      'חדר ישיבות',
      'משימה',
      'טיקט',
      'פרויקט',
      'דדליין',
      'תעדוף',
      'ספרינט',
      'סטנד אפ',
      'רטרו',
      'באקלוג',
      'דמו',
      'אקסל',
      'וורד',
      'קובץ',
      'טבלה',
      'דוח',
      'מדפסת',
      'סורק',
      'מהדק',
      'לוח מחיק',
      'טוש',
      'מנהל',
      'עובד חדש',
      'משאבי אנוש',
      'לקוח',
      'ספק',
      'ראיון',
      'קורות חיים',
      'קידום',
      'העלאה',
      'בונוס',
      'משרד',
      'עבודה מרחוק',
      'היברידי',
      'יום חופש',
      'מחלה',
      'מטבחון',
      'מכונת קפה',
      'ארוחת צהריים',
      'רכילות',
      'האפי האוור',
    ]),
    LocalCategory('technology_digital', 'טכנולוגיה ודיגיטל', [
      'סמארטפון',
      'טאבלט',
      'לפטופ',
      'שעון חכם',
      'אוזניות',
      'וויי פיי',
      'בלוטוס',
      'נתב',
      'נקודה חמה',
      'איירדרופ',
      'מטען',
      'כבל',
      'סוללה',
      'מתאם',
      'פאוור בנק',
      'מצלמה',
      'זיהוי פנים',
      'פנס',
      'התראה',
      'צילום מסך',
      'וואטסאפ',
      'טלגרם',
      'אינסטגרם',
      'טיקטוק',
      'דיסקורד',
      'דפדפן',
      'גוגל',
      'חיפוש',
      'טאבים',
      'קוקיז',
      'סיסמה',
      'קוד אימות',
      'הצפנה',
      'פיירוול',
      'אנטי וירוס',
      'ענן',
      'גיבוי',
      'אחסון',
      'סנכרון',
      'הורדה',
      'מודל',
      'פרומפט',
      'צ\'אט בוט',
      'מחולל תמונות',
      'עוזר קולי',
      'גיטהאב',
      'דוקר',
      'ממשק',
      'שרת',
      'מסד נתונים',
    ]),
    LocalCategory('travel_vacation', 'חופשה ונסיעות', [
      'דרכון',
      'כרטיס טיסה',
      'כרטיס עלייה',
      'ויזה',
      'ביטוח נסיעות',
      'צ\'ק אין',
      'גייט',
      'בידוק',
      'דיוטי פרי',
      'מסוע',
      'המראה',
      'נחיתה',
      'קונקשן',
      'עיכוב',
      'ג\'ט לג',
      'מזוודה',
      'טרולי',
      'תיק גב',
      'תג מזוודה',
      'משקל עודף',
      'מלון',
      'הוסטל',
      'דירה',
      'קמפינג',
      'ריזורט',
      'קבלה',
      'לובי',
      'חדר',
      'מפתח',
      'ארוחת בוקר',
      'חוף',
      'בריכה',
      'שמשייה',
      'מגבת',
      'קרם הגנה',
      'מפה',
      'מדריך',
      'מוזיאון',
      'תצפית',
      'מזכרת',
      'בוקינג',
      'דירת נופש',
      'הזמנה',
      'ביקורת',
      'ביטול',
      'שייט',
      'רכבל',
      'סקי',
      'טיול רגלי',
      'רוד טריפ',
    ]),
    LocalCategory('places', 'מקומות בעולם', [
      'פריז',
      'לונדון',
      'רומא',
      'ברצלונה',
      'אמסטרדם',
      'פראג',
      'וינה',
      'בודפשט',
      'ברלין',
      'קרקוב',
      'סנטוריני',
      'מיקונוס',
      'איביזה',
      'מלטה',
      'קפריסין',
      'טוקיו',
      'סיאול',
      'בנגקוק',
      'סינגפור',
      'הונג קונג',
      'ניו יורק',
      'לוס אנג\'לס',
      'מיאמי',
      'לאס וגאס',
      'טורונטו',
      'המלדיביים',
      'באלי',
      'הוואי',
      'פוקט',
      'סיישל',
      'גרנד קניון',
      'מפלי הניאגרה',
      'סהרה',
      'אמזונס',
      'פיורדים',
      'הקולוסיאום',
      'הפירמידות',
      'מאצ\'ו פיצ\'ו',
      'האקרופוליס',
      'פטרה',
      'מגדל אייפל',
      'ביג בן',
      'טיימס סקוור',
      'בורג\' ח\'ליפה',
      'סגרדה פמיליה',
      'אוורסט',
      'הדולומיטים',
      'איסלנד',
      'פטגוניה',
      'לפלנד',
    ]),
    LocalCategory('dating_relationships', 'דייטים וזוגיות', [
      'מאץ\'',
      'סווייפ',
      'פרופיל',
      'ביו',
      'תמונה',
      'הודעה',
      'לייק',
      'תגובה',
      'הודעה פרטית',
      'מספר טלפון',
      'בית קפה',
      'בר',
      'מסעדה',
      'קולנוע',
      'הליכה',
      'קראש',
      'כימיה',
      'פרפרים',
      'משיכה',
      'התאהבות',
      'מחמאה',
      'מבט',
      'חיוך',
      'מגע',
      'נשיקה',
      'סינון',
      'גוסטינג',
      'דאבל טקסט',
      'ייבוש',
      'חסימה',
      'אמון',
      'קנאה',
      'ריב',
      'פיוס',
      'פשרה',
      'דייט ראשון',
      'ידידות',
      'פרנדזון',
      'אקס',
      'קאמבק',
      'להכיר הורים',
      'מגורים משותפים',
      'הצעה',
      'טבעת',
      'חתונה',
      'שקר',
      'סוד',
      'חשד',
      'תירוץ',
      'דגל אדום',
    ]),
    LocalCategory('nightlife', 'לילה ובילויים', [
      'בר',
      'פאב',
      'מועדון',
      'קריוקי',
      'מסיבת בית',
      'תור',
      'סלקציה',
      'מאבטח',
      'צמיד',
      'הזמנה',
      'די ג\'יי',
      'רחבה',
      'רמקול',
      'באס',
      'פלייליסט',
      'כוס',
      'בקבוק',
      'קוקטייל',
      'בירה',
      'שוט',
      'ניאון',
      'לייזר',
      'עשן',
      'קונפטי',
      'פלאש',
      'ריקוד',
      'סלפי',
      'פלרטוט',
      'צחוקים',
      'היכרות',
      'מונית',
      'פיצה',
      'אפטר',
      'זריחה',
      'האנגאובר',
      'יום הולדת',
      'מסיבת רווקים',
      'מסיבת רווקות',
      'פסטיבל',
      'מסיבת גג',
      'ביליארד',
      'באולינג',
      'ארקייד',
      'סטנדאפ',
      'קזינו',
      'חשבון',
      'טיפ',
      'טרמפ',
      'מטען',
      'מים',
    ]),
    LocalCategory('weddings_events', 'חתונות ואירועים', [
      'הצעה',
      'טבעת',
      'אירוסין',
      'תאריך',
      'הזמנה',
      'חופה',
      'כתובה',
      'רב',
      'טבעת נישואין',
      'שבירת כוס',
      'כלה',
      'חתן',
      'שמלה',
      'חליפה',
      'הינומה',
      'פרחים',
      'נרות',
      'בלונים',
      'קונפטי',
      'מרכז שולחן',
      'אולם',
      'גן אירועים',
      'קבלת פנים',
      'רחבה',
      'בר',
      'קייטרינג',
      'בופה',
      'מנה',
      'קינוח',
      'עוגה',
      'צלם',
      'וידאו',
      'מגנטים',
      'עמדת צילום',
      'אלבום',
      'די ג\'יי',
      'שיר כניסה',
      'סלואו',
      'ריקוד ראשון',
      'פלייליסט',
      'מעטפה',
      'מתנה',
      'ברכה',
      'סידור שולחן',
      'אישור הגעה',
      'חינה',
      'יום הולדת',
      'בר מצווה',
      'בת מצווה',
      'מסיבת רווקים',
    ]),
    LocalCategory('fashion_grooming', 'אופנה וטיפוח', [
      'טי שירט',
      'חולצה מכופתרת',
      'סוודר',
      'קפוצ\'ון',
      'גופייה',
      'ג\'ינס',
      'מכנסיים',
      'שורטס',
      'חצאית',
      'טייץ',
      'מעיל',
      'ג\'קט',
      'בלייזר',
      'וסט',
      'מעיל גשם',
      'סניקרס',
      'עקבים',
      'מגפיים',
      'סנדלים',
      'כפכפים',
      'כובע',
      'משקפי שמש',
      'חגורה',
      'צעיף',
      'תיק',
      'שעון',
      'שרשרת',
      'צמיד',
      'טבעת',
      'עגילים',
      'מייקאפ',
      'שפתון',
      'מסקרה',
      'סומק',
      'אייליינר',
      'תספורת',
      'פן',
      'מחליק',
      'זקן',
      'גילוח',
      'לק',
      'מניקור',
      'קרם',
      'בושם',
      'דאודורנט',
      'מידה',
      'מותג',
      'סייל',
      'קולקציה',
      'תא מדידה',
    ]),
    LocalCategory('gaming', 'גיימינג', [
      'פלייסטיישן',
      'אקסבוקס',
      'סוויץ\'',
      'מחשב',
      'מובייל',
      'יריות',
      'מירוצים',
      'ספורט',
      'אסטרטגיה',
      'הישרדות',
      'לובי',
      'קלאן',
      'פארטי',
      'מאץ\'',
      'ראנק',
      'פריימים',
      'פינג',
      'לאג',
      'שרת',
      'גרפיקה',
      'לוט',
      'ספאון',
      'ריספאון',
      'קאמפינג',
      'גריינד',
      'שלב',
      'בוס',
      'משימה',
      'ניסיון',
      'סקיל',
      'סקין',
      'דמות',
      'נשק',
      'אמוט',
      'באטל פאס',
      'תוסף',
      'הרחבה',
      'מטבעות',
      'חנות',
      'חינמי',
      'חיים',
      'נקודת שמירה',
      'שמירה',
      'פסילה',
      'ניקוד',
      'ניצחון',
      'הפסד',
      'טורניר',
      'לוח מובילים',
      'משחק חוזר',
    ]),
    LocalCategory('music', 'מוזיקה', [
      'גיטרה',
      'בס',
      'כינור',
      'צ\'לו',
      'יוקולילי',
      'פסנתר',
      'קלידים',
      'אורגן',
      'סינתיסייזר',
      'אקורדיון',
      'תופים',
      'טמבורין',
      'משולש',
      'בונגוס',
      'קסילופון',
      'סקסופון',
      'חצוצרה',
      'חליל',
      'קלרינט',
      'מפוחית',
      'במה',
      'מיקרופון',
      'קהל',
      'הדרן',
      'מאחורי הקלעים',
      'אולפן',
      'אוזניות',
      'מיקסר',
      'הקלטה',
      'אוטו טיון',
      'פזמון',
      'בית',
      'פתיח',
      'גשר',
      'סולו',
      'אלבום',
      'סינגל',
      'פלייליסט',
      'רמיקס',
      'קאבר',
      'פופ',
      'רוק',
      'היפ הופ',
      'טראנס',
      'ג\'אז',
      'די ג\'יי',
      'קריוקי',
      'פסטיבל',
      'הופעה',
      'מסיבה',
    ]),
    LocalCategory('nostalgia', 'נוסטלגיה', [
      'ווקמן',
      'דיסקמן',
      'גיים בוי',
      'נוקיה',
      'טמגוצ\'י',
      'קסטה',
      'וידאו',
      'דיסקט',
      'דיסק',
      'פילם',
      'אייסיקיו',
      'מסנג\'ר',
      'חיוג',
      'מייספייס',
      'אינטרנט אקספלורר',
      'וינדוס',
      'וינאמפ',
      'מוקשים',
      'סוליטר',
      'פיינט',
      'רינגטון',
      'מסרון',
      'אינפרא אדום',
      'מסך ירוק',
      'אנטנה',
      'פוגים',
      'גולות',
      'יויו',
      'אלבום מדבקות',
      'קלפי פוקימון',
      'פאקמן',
      'טטריס',
      'סנייק',
      'ספייס אינויידרס',
      'פינבול',
      'קלאס',
      'חבל',
      'גומי',
      'חמש אבנים',
      'מחבואים',
      'טלפון קווי',
      'טלפון ציבורי',
      'טלכרט',
      'ביפר',
      'משיבון',
      'פולארויד',
      'מצלמה חדפעמית',
      'אלבום תמונות',
      'גליל פילם',
      'פיתוח תמונות',
    ]),
    LocalCategory('israeli_slang', 'סלנג ישראלי', [
      'סבבה',
      'אחלה',
      'וואלה',
      'תכלס',
      'יאללה',
      'פגז',
      'אש',
      'חבל"ז',
      'קטלני',
      'מטורף',
      'אחי',
      'גבר',
      'נשמה',
      'כפרה',
      'מלך',
      'חופר',
      'כבד',
      'נודניק',
      'קרציה',
      'סחי',
      'סטלן',
      'צ\'יל',
      'זורם',
      'מבסוט',
      'סתלבט',
      'פדיחה',
      'פשלה',
      'באסה',
      'נדפק',
      'בושות',
      'חרטה',
      'בלוף',
      'קומבינה',
      'פראייר',
      'הזוי',
      'להבריז',
      'לייבש',
      'להתפלח',
      'לפרגן',
      'להתקמבן',
      'קריזה',
      'ג\'ננה',
      'שבוז',
      'מורעל',
      'לחוץ',
      'קרינג\'',
      'פלקס',
      'גוסטינג',
      'רואסט',
      'וייב',
    ]),
    LocalCategory('idf_service', 'צה"ל ושירות', [
      'צו ראשון',
      'גיוס',
      'בקו"ם',
      'שרשרת חיול',
      'חוגר',
      'מדים',
      'דיסקית',
      'כומתה',
      'קיטבג',
      'נעליים צבאיות',
      'טירונות',
      'מסדר',
      'מטווח',
      'מסע',
      'תרגיל',
      'מפקד',
      'מ"מ',
      'מ"פ',
      'רס"ר',
      'רס"פ',
      'שמירה',
      'תורנות',
      'מטבח',
      'ניקיון',
      'שק"ם',
      'אפטר',
      'חמשוש',
      'רגילה',
      'גימלים',
      'יציאה',
      'ריתוק',
      'מחבוש',
      'משפט',
      'דיגום',
      'נפקדות',
      'פז"ם',
      'צעיר',
      'ותיק',
      'מורעל',
      'שבוז',
      'קרבי',
      'ג\'ובניק',
      'בסיס פתוח',
      'בסיס סגור',
      'מילואים',
      'ת"ש',
      'קב"ן',
      'מש"קית ת"ש',
      'קצין מיון',
      'שחרור',
    ]),
    LocalCategory('film_tv', 'קולנוע וטלוויזיה', [
      'סרט',
      'סדרה',
      'פרק',
      'עונה',
      'ספיישל',
      'קומדיה',
      'דרמה',
      'אימה',
      'אקשן',
      'מתח',
      'במאי',
      'תסריטאי',
      'מפיק',
      'שחקן',
      'ניצב',
      'מצלמה',
      'תאורה',
      'מיקרופון',
      'תפאורה',
      'איפור',
      'גיבור',
      'נבל',
      'דמות',
      'עלילה',
      'טוויסט',
      'טריילר',
      'ספוילר',
      'כתוביות',
      'דיבוב',
      'קרדיטים',
      'סיקוול',
      'פריקוול',
      'רימייק',
      'ספין אוף',
      'טרילוגיה',
      'ריאליטי',
      'שעשועון',
      'חדשות',
      'טוק שואו',
      'דוקו',
      'נטפליקס',
      'דיסני',
      'יוטיוב',
      'אמזון פריים',
      'סטרימינג',
      'פופקורן',
      'כרטיס',
      'אולם',
      'מסך',
      'מושב',
    ]),
    LocalCategory('sports', 'ספורט וכושר', [
      'כדורגל',
      'כדורסל',
      'כדורעף',
      'כדוריד',
      'הוקי',
      'טניס',
      'פאדל',
      'פינג פונג',
      'בדמינטון',
      'סקווש',
      'אגרוף',
      'ג\'ודו',
      'קראטה',
      'טאקוונדו',
      'היאבקות',
      'שחייה',
      'גלישה',
      'חתירה',
      'קיאק',
      'צלילה',
      'ריצה',
      'אופניים',
      'מרתון',
      'טריאתלון',
      'הליכה ספורטיבית',
      'הליכון',
      'משקולת',
      'מוט',
      'קטלבל',
      'גומייה',
      'סקוואט',
      'דדליפט',
      'לחיצת חזה',
      'מתח',
      'פלאנק',
      'סקי',
      'סנובורד',
      'החלקה אמנותית',
      'מזחלות',
      'קרלינג',
      'גולף',
      'חצים',
      'באולינג',
      'ביליארד',
      'קשתות',
      'שופט',
      'שריקה',
      'לוח תוצאות',
      'מדליה',
      'פודיום',
    ]),
  ],
};

/// A language's categories; an unknown one gets "he"'s.
List<LocalCategory> localCategoriesFor(String language) =>
    localContent[language] ?? localContent['he']!;

// Alternate spellings accepted only for the impostor's final guess, in
// every language.
const localGuessAliases = <String, List<String>>{
  'Omelette': ['Omelet'],
  'Donut': ['Doughnut'],
  'Mayo': ['Mayonnaise'],
  'Air conditioner': ['AC', 'Aircon'],
  'Cafeteria': ['Canteen'],
  'Resume': ['Résumé', 'CV'],
  'Smartphone': ['Smart phone'],
  'Fiance': ['Fiancee', 'Fiancé', 'Fiancée'],
  'Hoodie': ['Hoody'],
  'Pokemon cards': ['Pokémon cards'],
  'Donkey Kong': ['DK'],
  'Theater': ['Theatre'],
  'Soccer': ['Football'],
  'Ping pong': ['Table tennis'],
  'פאד תאי': ['פאדטאי', 'Pad Thai'],
  'אייר פרייר': ['Air Fryer'],
  'סלאק': ['Slack'],
  'טימס': ['Teams', 'מיקרוסופט טימס'],
  'סטנד אפ': ['סטנדאפ', 'Standup', 'Stand Up'],
  'משאבי אנוש': ['HR'],
  'וויי פיי': ['וייפיי', 'וויפי', 'WiFi', 'Wi-Fi', 'ווייפיי'],
  'בלוטוס': ['בלוטות', 'Bluetooth'],
  'נקודה חמה': ['הוטספוט', 'Hotspot', 'Hot Spot'],
  'איירדרופ': ['אירדרופ', 'AirDrop'],
  'פאוור בנק': ['פאוורבנק', 'Power Bank', 'Powerbank'],
  'צ\'אט בוט': ['צ\'אטבוט', 'Chatbot', 'Chat Bot'],
  'גיטהאב': ['GitHub'],
  'דוקר': ['Docker'],
  'ג\'ט לג': ['Jet Lag'],
  'בוקינג': ['Booking'],
  'רוד טריפ': ['Road Trip'],
  'די ג\'יי': ['DJ'],
  'יום הולדת': ['יומולדת'],
  'בר מצווה': ['ברמצוה'],
  'בת מצווה': ['בתמצוה'],
  'טי שירט': ['T-Shirt', 'T Shirt', 'טישרט', 'טישירט'],
  'באטל פאס': ['Battle Pass'],
  'נקודת שמירה': ['צ\'קפוינט', 'Checkpoint'],
  'לוח מובילים': ['לידרבורד', 'Leaderboard'],
  'משחק חוזר': ['רימאץ\'', 'Rematch'],
  'אוטו טיון': ['אוטוטיון', 'Auto-Tune', 'Autotune'],
  'היפ הופ': ['Hip Hop'],
  'גיים בוי': ['Game Boy'],
  'אייסיקיו': ['איסיקיו', 'ICQ'],
  'מייספייס': ['MySpace'],
  'אינטרנט אקספלורר': ['אקספלורר', 'Internet Explorer'],
  'וינדוס': ['ווינדוס', 'Windows'],
  'וינאמפ': ['ווינאמפ', 'Winamp'],
  'פיינט': ['Paint'],
  'פאקמן': ['פקמן', 'Pac-Man', 'Pacman'],
  'ספייס אינויידרס': ['ספייס אינוויידרס', 'Space Invaders'],
  'סיקוול': ['סיקואל', 'Sequel'],
  'ספין אוף': ['ספינאוף', 'Spin-off', 'Spinoff'],
  'טוק שואו': ['Talk Show'],
  'אמזון פריים': ['פריים וידאו', 'Amazon Prime', 'Prime Video'],
  'לחיצת חזה': ['בנץ פרס', 'בנץ\' פרס', 'בנצ\'פרס', 'Bench Press'],
};
